version: "2"
services:
  open_jtalk:
    image: erefy/open-jtalk:latest
    container_name: opne_jtalk
    volumes:
      - ./output:/data/open_jtalk/output
    volumes_from:
      - htsvoice
      - dictionary
  htsvoice:
    image: erefy/htsvoice:latest
    container_name: htsvoice
  dictionary:
    image: erefy/dictionary:latest
    container_name: dictionary
